language: python

python:
    - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls

script: coverage run --source rwalocation  rwalocation/main.py

after_success:
    coveralls